import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',   // lets content sit under the notch/home indicator
}

const SITE_URL = 'https://community.ghttrading.co'
const SITE_DESC = 'Premium gold (XAUUSD) trading signals, live market analysis, education, and a community of traders. Free for ACCM members.'

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'GHT Trading Community',
    template: '%s · GHT Trading',
  },
  description: SITE_DESC,
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'GHT Trading',
  },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'GHT Trading Community',
    title: 'GHT Trading Community',
    description: SITE_DESC,
    // og:image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'GHT Trading Community',
    description: SITE_DESC,
  },
  // Favicon/app icons come from src/app/icon.png and src/app/apple-icon.png.
}

// Runs before paint to set the theme from the saved choice (or the OS
// preference), avoiding a flash of the wrong theme on first load.
const themeInit = `(function(){try{var t=localStorage.getItem('theme');if(t!=='light'&&t!=='dark'){t=window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}document.documentElement.dataset.theme=t;}catch(e){}})();`

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
